package other;

        import org.openqa.selenium.By;
        import org.openqa.selenium.WebDriver;
        import org.openqa.selenium.WebElement;
        import org.openqa.selenium.chrome.ChromeDriver;
        import org.openqa.selenium.chrome.ChromeOptions;
        import org.openqa.selenium.support.ui.ExpectedConditions;
        import org.openqa.selenium.support.ui.WebDriverWait;
        import org.testng.annotations.*;

        import java.util.ArrayList;
        import java.util.List;

public class Offers {
    WebDriver driver;
    List<String> urlNotOffers = new ArrayList<String>();

    @DataProvider(name = "url")
    public Object[] createData1() {
        return new Object[]{
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-blue/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda-compute/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-p300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-elements-portable-30-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-dt01acaxxx/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-canvio-ready-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-nasware-red/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-black-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-canvio-basics-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-storejet-25m3-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-blue-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-sv35/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-x300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-canvio-connect-ii-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-canvio-alu-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-enterprise-capacity-35-hdd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-hv620-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-maxtor-m3-portable-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-black/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-av-gp/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-travelstar-7k1000-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd650-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-firecuda/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-ironwolf/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-my-passport-ultra-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-expansion-desk-30/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-storejet-25h3p-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-elements-desktop/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-skyhawk/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-backup-plus-hub/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-backup-plus-slim-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda-compute-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-firecuda-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-caviar-black/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-expansion-portable-hard-drive-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-gold/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-my-passport-new-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-caviar-blue/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-momentus-thin-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-purple/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-usb-c-for-mac-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-triple-usb-30-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-md04acaxxx/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-2big-thunderbolt-2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-porsche-design-p9230/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-enterprise-capacity-hdd-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-canvio-premium-for-mac-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-diamond-d06-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-c15k600-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-he8/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-surveillance/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda-720014/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lenovo-thinkserver-hdd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda-720012/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-server-sata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-d2-thunderbolt-3/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/fujitsu-sata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-choice-hc660-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-storejet-25c3-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-server-sas-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd700-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-thunderbolt-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-pipeline-hd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-mg03acaxxx/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-armor-a15-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-porsche-design-mobile-drive-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-armor-a65-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-armor-a60-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-hv100-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-my-book-duo/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-cheetah-15k7/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-constellation-es3/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-thunderbolt-usb-c-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-c10k900-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-msa-sas-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/fujitsu-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-al14sexxxxnx-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-al13sxbxxxn-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-al13se-series-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-mg04scaxxxe/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-backup-plus-desk-30/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-porsche-design-p9233/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-stream-s03-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd710p-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-storejet-25a3-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-mini-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-armor-a85-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-ironwolf-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-mg04acaxxxxe/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-d2-usb-30/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-midline-sata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/huawei-server-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-sata-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-enterprise-performance-10k-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lenovo-thinkserver-hdd-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-server-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-storejet-35t3/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-armor-a80-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/sony-hd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-canvio-premium-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd650-usb-31-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-backup-plus-ultra-slim-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-scorpio-blue-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-mobile-hdd-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-sas-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-sata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-enterprise-performance-15k-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ibm-near-line/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-msa-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/fujitsu-sas-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-midline-sata-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ibm-server/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/verbatim-store-n-go-30-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-n300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda-pro-compute/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-armor-a30-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-he10/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-re/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-travelstar-z7k500-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-porsche-design-mobile-type-c-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd710-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ibm-express-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-video/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-dt01abaxxxv/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-elements-portable-se-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-nas-hdd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-7k6000/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd720-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-my-passport-wireless-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-7k2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-l200-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-travelstar-z5k500-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-red-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-deskstar-nas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-e300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda-green/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-barracuda/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-green/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/istorage-diskashur/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-purple-nv/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-laptop-sshd-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-basic-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ibm-v3700-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-diamond-d03-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/istorage-diskashur-dt/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-porsche-design-p9220-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-m6710-sas-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-diamond-d20-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-midline-sas-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-midline-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ibm-server-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-porsche-design-desktop/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-dashdrive-durable-hd710a-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-diamond-d05-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-c10k1800-25/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-d2-quadra-usb-30/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-mg03scaxxx/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/seagate-xbox-game-pass-special-edition/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-850-evo/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-ssdnow-uv400/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-slim-s60/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-960-evo-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-850-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-hyperx-savage-ssd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ocz-rd400a-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-hyperx-fury/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-slim-s55/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-ignition-plus/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-revival-2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-velox-v60/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-green-ssd-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-xpg-sx8000-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-ssdnow-ms200-msata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-nv11-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/amd-radeon-r3/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-ultimate-su800/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-ultimate-su700/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-xpg-gammix-s10-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-535-series-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-220s/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-850-evo-msata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-m8peg-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-leap/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-portable-t5/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-ssdnow-g2-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/corsair-force-series-ls/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-540s-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-a400/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-960-pro-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/corsair-force-series-mp500-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-850-evo-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-s3c/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-premier-sp580/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-530-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-splash-2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-green-ssd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-ultimate-su900/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-rd400-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-panther-as350/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-climb/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-kc1000-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/goodram-cx200/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s3610/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-z280-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-s2g-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-540s-series-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/goodram-iridium-gen2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-as2280-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/patriot-spark/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-s3g-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-kc1000-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-s2c/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-esd400/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/micron-1100/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-m7-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s3520/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-enterprise-line-5007-pro-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/patriot-burst/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/corsair-force-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-premier-pro-sp920/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/goodram-cx300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s3710/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-for-server/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p3500-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s3510/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-thunderbolt-usb-c/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-msa370-msata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-proii-series-as510s/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-360s/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-535-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-m8sey-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-m8segn-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/crucial-mx300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-enterprise-line-5007-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-ss200-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/sandisk-cloudspeed-eco-gen-ii/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-ultimate-su800-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-pm1633/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-mts820-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-enterprise-line-s10pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-jetdrive-520-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-sm863a/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-hyperx-predator-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/palit-uvs/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-q300-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-hyperx-predator-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-panther-as340/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-optane-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-mts600-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/sandisk-ultra-ii/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-blue-ssd-3d-nand/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p4501/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p3100-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/micron-5100-eco/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/micron-5100-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-s11t-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-370/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/patriot-hellfire-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-ssdnow-v300/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-m8pey-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-revival/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-mte850-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/foxline-x3-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p3608-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-ast280-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-mts800-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/corsair-force-series-le/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-slim-s80/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s3500/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/sandisk-cloudspeed-ultra-gen-ii/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-pm1633a/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-xpg-sx950/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/goodram-iridium-pro/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-blue-ssd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/patriot-flare/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-black-ssd-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-portable-t3/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/goodram-cl100/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-ssdnow-kc400/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-545s-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/foxline-x6-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-600p-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-premier-sp600/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p4500-u2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-s3-18/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s4600/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ocz-vx500/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/plextor-px-m8seg-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-s4500/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/kingston-dc400/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-ssd800mhb-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lacie-rugged-thunderbolt/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-525-msata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-premier-pro-sp900/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/micron-5100-max/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-storejet-500/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/micron-1100-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-420i/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-esd220c/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/fujitsu-server/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-750-series-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p3600-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-puls/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/lenovo-thinkserver/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-jetdrive-720-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/ibm-for-server/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-370s/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-s11-msata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-velox-v55/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-xpg-sx7000-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/smartbuy-ignition-4/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-blue-ssd-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/sandisk-plus-tlc/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-230/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/silicon-power-slim-s70/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/apacer-panther-as330/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/wd-blue-ssd-3d-nand-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p4600-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-durable-sd700/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/corsair-neutron-series-xti/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-sv620h/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p3700-pcie/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-ssd-340/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/transcend-jetdrive-725-m2/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/istorage-diskashur-ssd/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-value-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/intel-dc-p4600/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-pm863a/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hp-for-server-35/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-value-sata/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/dell-value-sata-35/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hitachi-ultrastar-ssd1600mr-sas/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/toshiba-hk4r-series/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samsung-pm863/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/hynix-sl308/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-durable-sd600/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/samurai-guarddo/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/a-data-xpg-sd700x/kupit",
                "https://product-test.ru/zhestkie-diski--ssd-i-setevye-nakopiteli/crucial-mx300-m2/kupit"
        };
    }

    @BeforeClass
    public void config() {
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless");
        driver = new ChromeDriver(
                options
        );
    }

    @AfterClass
    public void tearDown() {
        System.out.println(urlNotOffers);
        driver.quit();
    }

    @Test(dataProvider = "url")
    public void testOffers(String URL) throws InterruptedException {
        try {
            driver.get(URL
                     + "?city=Казань"
            );
            driver.findElements(By.className("image-buy"));

            // WebElement offersMessageElement = (new WebDriverWait(driver, 3)).until(ExpectedConditions.presenceOfElementLocated(By.id("buy_button")));
            WebElement offersMessageElement = (new WebDriverWait(driver, 3)).until(ExpectedConditions.presenceOfElementLocated(By.xpath("/html[@class='no-js html-adaptive desktop landscape']/body/div[@class='out']/div[@class='container']/div[@id='m-wrapper']/div[@class='center content-wrapper']/div[2]/div[@class='tabs h-block m-hide']/div[@class='tabs__item active']/span[@class='tabs__link']/span[@class='tabs__counter buy_tabs__counter']")));
            Thread.sleep(3000);
            // driver.manage().timeouts().implicitlyWait(6, TimeUnit.SECONDS);
            WebElement d = driver.findElement(By.xpath("/html[@class='no-js html-adaptive desktop landscape']/body/div[@class='out']/div[@class='container']/div[@id='m-wrapper']/div[@class='center content-wrapper']/div[2]/div[@class='tabs h-block m-hide']/div[@class='tabs__item active']/span[@class='tabs__link']/span[@class='tabs__counter buy_tabs__counter']"));

            if (d.getText().length() == 0) {
                Thread.sleep(5000);
            }
//        if (d.getText().equals("(0)")) {
//        urlNotOffers.add(URL);
//            Assert.assertTrue(false);
//        } else System.out.println("предложения есть!");
            System.out.println(d.getText());
        } catch (org.openqa.selenium.NoSuchWindowException e) {
            config();
        }
    }
}

